name: Auto Pull on Push

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang yang sesuai

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: SSH into Ubuntu Server and Pull Changes
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@203.175.11.72 'cd /var/www/Toko-Emas-3 && git pull'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
