name: Auto Pull

on:
  push:
    branches:
      - main  
jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull changes
        run: git pull
